### ISSUE TITLE
Ambiguous routing match exception

### ISSUE THREAD

**Issue by rudism** [petrsvihlik/jsConnectAspNetCoreMvc#14]
With a fresh install of Vanilla 3.3 pointing to a `netcoreapp3.1` mvc.net application (dotnet v3.1.106), I'm getting this error whenever Vanilla calls the `/jsconnect/authenticate` endpoint. Am I missing something to make it work?

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

jsConnect.Controllers.JsConnectController.AuthenticateAsync (jsConnect)
jsConnect.Controllers.JsConnectController.Authenticate (jsConnect)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by rudism** [comment]
I got this working with my mvc project. Opened a PR with the changes I had to make before things started working in case you want to incorporate them.
